spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
  application:
    name: freemark-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.111:3306/dev_gmd_fimsdb?useUnicode=true&characterEncoding=utf-8
    username: gmd_fims
    password: gmd_fims123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lf.freemarker.bean  #所有entity别名所在包
  configuration:
    map-underscore-to-camel-case: true



server:
  port: 1998

classpath: D:/src/generate/code
